import leantermination.Basic
import leantermination.Datastructures.IntegerProgram
import leantermination.Parsing.Preparse
import leantermination.Parsing.ITSParse
import leantermination.Termination.AcyclicIntegerProgram
import leantermination.Termination.LASWTermination
